function rolld4(){
    let valor = Math.floor(Math.random() * 4) + 1
    let res = document.getElementById('ressultado')
    res.innerHTML = `Resultado: ${valor}`
}
function rolld6(){
    let valor = Math.floor(Math.random() * 6) + 1
    let res = document.getElementById('ressultado')
    res.innerHTML = `Resultado: ${valor}`
}
function rolld8(){
    let valor = Math.floor(Math.random() * 8) + 1
    let res = document.getElementById('ressultado')
    res.innerHTML = `Resultado: ${valor}`
}
function rolld10(){
    let valor = Math.floor(Math.random() * 10) + 1
    let res = document.getElementById('ressultado')
    res.innerHTML = `Resultado: ${valor}`
}
function rolld12(){
    let valor = Math.floor(Math.random() * 12) + 1
    let res = document.getElementById('ressultado')
    res.innerHTML = `Resultado: ${valor}`
}
function rolld20(){
    let valor = Math.floor(Math.random() * 20) + 1
    let res = document.getElementById('ressultado')
    res.innerHTML = `Resultado: ${valor}`
}

